name: CI from Arduino

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Pourquoi on lance le workflow"
        required: false
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: |
          echo "Hello depuis GitHub Actions !"
          echo "Reason: ${{ github.event.inputs.reason }}"